// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhbsde-111UvJChGGbYroTNj5xWIiPAuM',
    appId: '1:103847675068:web:9baad8c1bde00767bdbcb9',
    messagingSenderId: '103847675068',
    projectId: 'evenline-8a094',
    authDomain: 'evenline-8a094.firebaseapp.com',
    storageBucket: 'evenline-8a094.firebasestorage.app',
    measurementId: 'G-P5MZ8S4XKK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNf3mDfiyIOdE7Ns3H935HGHj-1KSaP2M',
    appId: '1:103847675068:android:70ffb991336e0b15bdbcb9',
    messagingSenderId: '103847675068',
    projectId: 'evenline-8a094',
    storageBucket: 'evenline-8a094.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhbsde-111UvJChGGbYroTNj5xWIiPAuM',
    appId: '1:103847675068:web:78073529c0c76c63bdbcb9',
    messagingSenderId: '103847675068',
    projectId: 'evenline-8a094',
    authDomain: 'evenline-8a094.firebaseapp.com',
    storageBucket: 'evenline-8a094.firebasestorage.app',
    measurementId: 'G-593F3WJPEN',
  );
}
